<a href="https://colab.research.google.com/github/BrezginaVera/Linal/blob/main/Homework5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#Домашнее задание 5 №1
import numpy as np
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A)
D[np.diag_indices(min(A.shape))] = s
print (f'Матрица D:\n{D}')
print (f'Матрица V:\n{V}')
print (f'Матрица U:\n{U}')

Матрица D:
[[8 0 0]
 [0 6 0]
 [0 0 2]
 [0 0 0]
 [0 0 0]]
Матрица V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]
Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]


In [16]:
#Домашнее задание 5 №2
import numpy as np
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
from numpy.linalg import norm
print(f'Норма Фробениуса:\n{norm(A, ord=None)}')
print(f'Норма Евклида:\n{norm(A, ord=1)}')

Норма Фробениуса:
11.045361017187261
Норма Евклида:
13.0
